---
title: "DHSB Technology Tables"
author: "Adam Northrup, Data Manager, ETAC"
date: "June 6, 2019"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = FALSE, include = FALSE, 
                      warning = FALSE, message = FALSE)
#####Read libraries
library(tidyverse)
library(sjlabelled)
library(rio)
library(openxlsx)
library(kableExtra)

#####Load data
load("acasi.RData")
source("DHSB Table Functions.R")
```

```{r processData}
tech <- acasi %>%
  filter(Set == 1) %>% #Remove participants without 06m assessment
  filter(!(is.na(HE_RC_HAL) | is.na(HE_RC_HSE))) %>%
  select(SITE1, SITE_RC, PID, starts_with("MTU"), starts_with("S56")) %>%
  mutate(S56_3 = fct_recode(as.factor(S56_3),
                            "Have cell phone, minutes, and data"    = "1",
                            "Have cell phone, minutes, and no data" = "2",
                            "Have cell phone, data, and no minutes" = "3",
                            "I share a phone"                       = "4",
                            "Don't have own cell, can borrow one"   = "5",
                            "Don't have own cell, can't borrow one" = "6",
                            "Refuse to answer"                      = "8")) %>%
  mutate_at(vars(one_of("S56_4", "S56_7", "S56_13", "S56_16", "S56_21")), 
            list(~as.factor)) %>%
  mutate_at(vars(one_of("S56_4", "S56_7", "S56_13", "S56_16", "S56_21")), 
            list(~fct_recode),
            "Several times a day"       = "1",
            "Once a day"                = "2",
            "Once every couple of days" = "3",
            "About once a week"         = "4",
            "Less than once a week"     = "5",
            "Never"                     = "6",
            "Refuse to answer"          = "8",
            "Skipped"                   = "9") %>%
  mutate(S56_11 = fct_recode(as.factor(S56_11),
                             "Facebook"           = "0",
                             "Facebook Messenger" = "1",
                             "Twitter"            = "2",
                             "Instagram"          = "3",
                             "Snapchat"           = "4",
                             "WhatsApp"           = "5",
                             "Skype"              = "6",
                             "Kik"                = "7",
                             "Vine"               = "8",
                             "Tumblr"             = "9",
                             "Pinterest"          = "10",
                             "Other"              = "11",
                             "Refuse to answer"   = "98",
                             "Skipped"            = "99"),
         S56_20 = fct_recode(as.factor(S56_20),
                             "Tinder"               = "1",
                             "Grindr"               = "2",
                             "Growler"              = "3",
                             "Jack'd"               = "4",
                             "Scruff"               = "5",
                             "Badoo"                = "6",
                             "Craigslist"           = "7",
                             "Plenty of Fish (POF)" = "8",
                             "Adam4Adam (A4a)"      = "9",
                             "Hinge"                = "10",
                             "Bumble"               = "11",
                             "Other"                = "12",
                             "Refuse to answer"     = "98",
                             "Skipped" = "99"),
         S56_23 = fct_recode(as.factor(S56_23),
                             "Every day, more than 1 hour" = "1",
                             "Every day, less than 1 hour" = "2",
                             "Almost every day"            = "3",
                             "A couple times a week"       = "4",
                             "Once a week"                 = "5",
                             "Less than once a week"       = "6",
                             "Never"                       = "7",
                             "Refuse to answer"            = "8"),
         S56_24XV = as.integer(S56_24XV))
```

```{r techSummary}
table3a <- bind_rows(
  table_ManyBinary(tech, n = 3, header = "Device Use", keep = "S56_1G",
                        variables = c("S56_1A" = "Cell Phone", 
                                      "S56_1B" = "Tablet", 
                                      "S56_1C" = "Other mobile device",
                                      "S56_1D" = "Laptop",
                                      "S56_1E" = "Desktop computer",
                                      "S56_1F" = "Other", 
                                      "S56_1G" = "No devices")),
  # table_ManyBinary(tech, n = 3, header = "Device Use Locations",
  #                       variables = c("S56_2A" = "Home", 
  #                                     "S56_2B" = "Where I'm staying", 
  #                                     "S56_2C" = "Other's house/apartment", 
  #                                     "S56_2D" = "Public place with WiFi", 
  #                                     "S56_2E" = "Internet cafe", 
  #                                     "S56_2F" = "Public library", 
  #                                     "S56_2G" = "School", 
  #                                     "S56_2H" = "Work", 
  #                                     "S56_2I" = "Other")),
  # table_OneFactor(tech, n = 3, varString = "S56_3",
  #                      header = "Cell Phone Access", 
  #                      keep = "Don't have own cell, can't borrow one"),
  table_OneFactor(tech, n = 3, varString = "S56_4",
                       header = "Frequency of Sending/Receiving Texts",
                       keep = "Never") %>%
    add_row(Variable = "Text Messaging", .before = 1),
  # table_ManyBinary(tech, n = 3, header = "Who You Text",
  #                       variables = c(
  #                         "S56_5A" = "Parents",
  #                         "S56_5B" = "Siblings, cousins, other family",
  #                         "S56_5C" = "Spouse/Boyfriend/Girlfriend",
  #                         "S56_5D" = "Casual sex partner, hook up, etc.",
  #                         "S56_5E" = "LGBTQ friends, community",
  #                         "S56_5F" = "Non-LGBTQ friends",
  #                         "S56_5G" = "People from home",
  #                         "S56_5H" = "People from online",
  #                         "S56_5I" = "Medical/Social service providers/staff",
  #                         "S56_5J" = "Co-workers",
  #                         "S56_5K" = "Teachers or school staff",
  #                         "S56_5L" = "Classmates/Friends from school",
  #                         "S56_5M" = "Banks/Billing/Utility companies",
  #                         "S56_5N" = "Client or dates for sex exchange",
  #                         "S56_5O" = "Other"
  #                       )),
  # table_ManyBinary(tech, n = 3, header = "What You Text About",
  #                       variables = c(
  #                         "S56_6A" = "Music, movies, TV",
  #                         "S56_6B" = "Work",
  #                         "S56_6C" = "School",
  #                         "S56_6D" = "Drinking, drugs, partying",
  #                         "S56_6E" = "Happy/Fun things w/ friends/family",
  #                         "S56_6F" = "Problems/Drama w/ friends/family",
  #                         "S56_6G" = "Social services",
  #                         "S56_6H" = "Love/Relationships",
  #                         "S56_6I" = "Sex",
  #                         "S56_6J" = "Sex work",
  #                         "S56_6K" = "Safe sex",
  #                         "S56_6L" = "Sexual identity/attraction",
  #                         "S56_6M" = "HIV status/care",
  #                         "S56_6N" = "Videos on LGBTQ topics",
  #                         "S56_6O" = "Videos on non-LGBTQ topics",
  #                         "S56_6P" = "Hormone therapy",
  #                         "S56_6Q" = "Other gender identity topics",
  #                         "S56_6R" = "Other"
  #                       )),
  table_OneFactor(tech, n = 3, varString = "S56_7",
                       header = "Frequency of Checking Email",
                       keep = "Never") %>%
    add_row(Variable = "Email", .before = 1)
  # table_ManyBinary(tech, n = 3, header = "Who You Email",
  #                       variables = c(
  #                         "S56_8A" = "Parents",
  #                         "S56_8B" = "Siblings, cousins, other family",
  #                         "S56_8C" = "Spouse/Boyfriend/Girlfriend",
  #                         "S56_8D" = "Casual sex partner, hook up, etc.",
  #                         "S56_8E" = "LGBTQ friends, community",
  #                         "S56_8F" = "Non-LGBTQ friends",
  #                         "S56_8G" = "People from home",
  #                         "S56_8H" = "People from online",
  #                         "S56_8I" = "Medical/Social service providers/staff",
  #                         "S56_8J" = "Co-workers",
  #                         "S56_8K" = "Teachers or school staff",
  #                         "S56_8L" = "Classmates/Friends from school",
  #                         "S56_8M" = "Banks/Billing/Utility companies",
  #                         "S56_8N" = "Client or dates for sex exchange",
  #                         "S56_8O" = "Other"
  #                       )),
  # table_ManyBinary(tech, n = 3, header = "What You Email About",
  #                       variables = c(
  #                         "S56_9A" = "Music, movies, TV",
  #                         "S56_9B" = "Work",
  #                         "S56_9C" = "School",
  #                         "S56_9D" = "Drinking, drugs, partying",
  #                         "S56_9E" = "Happy/Fun things w/ friends/family",
  #                         "S56_9F" = "Problems/Drama w/ friends/family",
  #                         "S56_9G" = "Social services",
  #                         "S56_9H" = "Love/Relationships",
  #                         "S56_9I" = "Sex",
  #                         "S56_9J" = "Sex work",
  #                         "S56_9K" = "Safe sex",
  #                         "S56_9L" = "Sexual identity/attraction",
  #                         "S56_9M" = "HIV status/care",
  #                         "S56_9N" = "Videos on LGBTQ topics",
  #                         "S56_9O" = "Videos on non-LGBTQ topics",
  #                         "S56_9P" = "Hormone therapy",
  #                         "S56_9Q" = "Other gender identity topics",
  #                         "S56_9R" = "Other"
  #                       ))
)
table3b <- bind_rows(
  # table_ManyBinary(x = tech, n = 3, header = "Social Networking Apps",
  #                       keep = "S56_10M",
  #                       variables = c(
  #                         "S56_10A" = "Facebook",
  #                         "S56_10B" = "Facebook Messenger",
  #                         "S56_10C" = "Twitter",
  #                         "S56_10D" = "Instagram",
  #                         "S56_10E" = "Snapchat",
  #                         "S56_10F" = "WhatsApp",
  #                         "S56_10G" = "Skype",
  #                         "S56_10H" = "Kik",
  #                         "S56_10I" = "Vine",
  #                         "S56_10J" = "Tumblr",
  #                         "S56_10K" = "Pinterest",
  #                         "S56_10L" = "Other",
  #                         "S56_10M" = "None"
  #                       )) %>%
  #   add_row(Variable = "General Social Networking (SN) Apps", .before = 1),
  table_OneFactor(x = tech, n = 3, header = "SN Used Most Often",
                        varString = "S56_11"),
  table_OneFactor(tech, n = 3, header = "SN Use Frequency",
                       varString = "S56_13"),
  # table_ManyBinary(tech, n = 3, header = "SN Activities",
  #                       variables = c(
  #                         "S56_12A" = "Update status",
  #                         "S56_12B" = "Search for people",
  #                         "S56_12C" = "Add or delete friends",
  #                         "S56_12D" = "Send/Receive private messages",
  #                         "S56_12E" = "Send/Receive public messages",
  #                         "S56_12F" = "Share pictures/video that you took",
  #                         "S56_12G" = "Share links/memes/GIFs/other media",
  #                         "S56_12H" = "Write shared notes",
  #                         "S56_12I" = "Comment/Like/Emoji friends' content",
  #                         "S56_12J" = "Browse profiles/newsfeed/ticker",
  #                         "S56_12K" = "Maintain privacy or other settings",
  #                         "S56_12L" = "Create/Maintain alternate profiles",
  #                         "S56_12M" = "Support LGBTQ groups/causes",
  #                         "S56_12N" = "Search hormone therapies",
  #                         "S56_12O" = "Search gender-related surgeries/procedures",
  #                         "S56_12P" = "Search HIV information",
  #                         "S56_12Q" = "Play games",
  #                         "S56_12R" = "Other"
  #                       )),
  # table_ManyBinary(tech, n = 3, header = "Communicate With Whom on SN Apps",
  #                       variables = c(
  #                         "S56_14A" = "Parents",
  #                         "S56_14B" = "Siblings, cousins, other family",
  #                         "S56_14C" = "Spouse/Boyfriend/Girlfriend",
  #                         "S56_14D" = "Casual sex partner, hook up, etc.",
  #                         "S56_14E" = "LGBTQ friends, community",
  #                         "S56_14F" = "Non-LGBTQ friends",
  #                         "S56_14G" = "People from home",
  #                         "S56_14H" = "People from online",
  #                         "S56_14I" = "Medical/Social service providers/staff",
  #                         "S56_14J" = "Co-workers",
  #                         "S56_14K" = "Teachers or school staff",
  #                         "S56_14L" = "Classmates/Friends from school",
  #                         "S56_14M" = "Banks/Billing/Utility companies",
  #                         "S56_14N" = "Client or dates for sex exchange",
  #                         "S56_14O" = "Other"
  #                       )),
  # table_ManyBinary(tech, n = 3, header = "Communicate About on SN Apps",
  #                       variables = c(
  #                         "S56_15A" = "Music, movies, TV",
  #                         "S56_15B" = "Work",
  #                         "S56_15C" = "School",
  #                         "S56_15D" = "Drinking, drugs, partying",
  #                         "S56_15E" = "Happy/Fun things w/ friends/family",
  #                         "S56_15F" = "Problems/Drama w/ friends/family",
  #                         "S56_15G" = "Social services",
  #                         "S56_15H" = "Love/Relationships",
  #                         "S56_15I" = "Sex",
  #                         "S56_15J" = "Sex work",
  #                         "S56_15K" = "Safe sex",
  #                         "S56_15L" = "Sexual identity/attraction",
  #                         "S56_15M" = "HIV status/care",
  #                         "S56_15N" = "Videos on LGBTQ topics",
  #                         "S56_15O" = "Videos on non-LGBTQ topics",
  #                         "S56_15P" = "Hormone therapy",
  #                         "S56_15Q" = "Other gender identity topics",
  #                         "S56_15R" = "Other"
  #                       )),
  table_OneFactor(tech, n = 3, header = "PM Use Frequency",
                       varString = "S56_16",
                       keep = "Never") %>%
    add_row(Variable = "Private Messaging (PM) Apps", .before = 1),
  # table_ManyBinary(tech, n = 3, header = "Communicate With Whom on PM Apps",
  #                       variables = c(
  #                         "S56_17A" = "Parents",
  #                         "S56_17B" = "Siblings, cousins, other family",
  #                         "S56_17C" = "Spouse/Boyfriend/Girlfriend",
  #                         "S56_17D" = "Casual sex partner, hook up, etc.",
  #                         "S56_17E" = "LGBTQ friends, community",
  #                         "S56_17F" = "Non-LGBTQ friends",
  #                         "S56_17G" = "People from home",
  #                         "S56_17H" = "People from online",
  #                         "S56_17I" = "Medical/Social service providers/staff",
  #                         "S56_17J" = "Co-workers",
  #                         "S56_17K" = "Teachers or school staff",
  #                         "S56_17L" = "Classmates/Friends from school",
  #                         "S56_17M" = "Banks/Billing/Utility companies",
  #                         "S56_17N" = "Client or dates for sex exchange",
  #                         "S56_17O" = "Other"
  #                       )),
  # table_ManyBinary(tech, n = 3, header = "Communicate About on PM Apps",
  #                       variables = c(
  #                         "S56_18A" = "Music, movies, TV",
  #                         "S56_18B" = "Work",
  #                         "S56_18C" = "School",
  #                         "S56_18D" = "Drinking, drugs, partying",
  #                         "S56_18E" = "Happy/Fun things w/ friends/family",
  #                         "S56_18F" = "Problems/Drama w/ friends/family",
  #                         "S56_18G" = "Social services",
  #                         "S56_18H" = "Love/Relationships",
  #                         "S56_18I" = "Sex",
  #                         "S56_18J" = "Sex work",
  #                         "S56_18K" = "Safe sex",
  #                         "S56_18L" = "Sexual identity/attraction",
  #                         "S56_18M" = "HIV status/care",
  #                         "S56_18N" = "Videos on LGBTQ topics",
  #                         "S56_18O" = "Videos on non-LGBTQ topics",
  #                         "S56_18P" = "Hormone therapy",
  #                         "S56_18Q" = "Other gender identity topics",
  #                         "S56_18R" = "Other"
  #                       )),
  # table_ManyBinary(x = tech, n = 3, header = "Dating/Hookup Apps Used",
  #                       keep = "S56_19N",
  #                       variables = c(
  #                         "S56_19A" = "Tinder",
  #                         "S56_19B" = "Grindr",
  #                         "S56_19C" = "Growler",
  #                         "S56_19D" = "Jack'd",
  #                         "S56_19E" = "Scruff",
  #                         "S56_19F" = "Badoo",
  #                         "S56_19G" = "Craigslist",
  #                         "S56_19H" = "Plenty of Fish (POF)",
  #                         "S56_19I" = "OkCupid",
  #                         "S56_19J" = "Adam4Adam (A4A)",
  #                         "S56_19K" = "Hinge",
  #                         "S56_19L" = "Bumble",
  #                         "S56_19M" = "Other",
  #                         "S56_19N" = "None"
  #                       )) %>%
  #   add_row(Variable = "Dating/Hookup Apps", .before = 1),
  # table_OneFactor(x = tech, n = 3, header = "Dating/Hookup App Used Most Often",
  #                       varString = "S56_20"),
  # table_OneFactor(tech, n = 3, header = "Dating/Hookup App Use Frequency",
  #                      varString = "S56_21"),
  # table_ManyBinary(tech, n = 3, header = "Dating/Hookup App Activities",
  #                       variables = c(
  #                         "S56_22A" = "Search for someone for sex",
  #                         "S56_22B" = "Search for client for sex for money/food/shelter/etc.",
  #                         "S56_22C" = "Search for someone to casually date",
  #                         "S56_22D" = "Search for someone for committed dating",
  #                         "S56_22E" = "Update your status",
  #                         "S56_22F" = "Add/Delete people, make new friends",
  #                         "S56_22G" = "Send/Receive private messages",
  #                         "S56_22H" = "Send/Receive public messages",
  #                         "S56_22I" = "Share pictures/video you took",
  #                         "S56_22J" = "Comment/Like/Emoji friends' content",
  #                         "S56_22K" = "Support LGBTQ groups/causes",
  #                         "S56_22L" = "Share links/memes/GIFs/other media",
  #                         "S56_22M" = "Browse profiles/newsfeed/ticker",
  #                         "S56_22N" = "Maintain privacy or other settings",
  #                         "S56_22O" = "Create/Maintain your profile",
  #                         "S56_22P" = "Create/Maintain alternate profiles",
  #                         "S56_22Q" = "Read about sexual health information",
  #                         "S56_22R" = "Talk about sexual health",
  #                         "S56_22S" = "Other"
  #                       )),
  table_OneFactor(tech, n = 3, header = "Frequency of Other Uses of Internet",
                       varString = "S56_23",
                       keep = "Never") %>%
    add_row(Variable = "Use Internet Other Than Messaging, Email, Social Networking, Dating",
            .before = 1)
  # table_ManyBinary(x = tech, n = 0, header = "Ever Used the Internet to...",
  #                       keep = c("S56_24XL", "S56_24XM", "S56_24XN", "S56_24XO",
  #                                "S56_24XV"),
  #                       variables = c(
  #                         "S56_24A"  = "Listen to music",
  #                         "S56_24B"  = "Bank or pay bills",
  #                         "S56_24C"  = "Look for work",
  #                         "S56_24D"  = "Look for housing",
  #                         "S56_24E"  = "Read news articles",
  #                         "S56_24F"  = "Look for place to party",
  #                         "S56_24G"  = "Look for a sex partner for pay",
  #                         "S56_24H"  = "Look for a sex partner not for pay",
  #                         "S56_24I"  = "Watch porn",
  #                         "S56_24J"  = "Watch videos on LGBTQ topics",
  #                         "S56_24K"  = "Watch videos on non-LGBTQ topics",
  #                         "S56_24XL" = "Look up information about sex/sexuality",
  #                         "S56_24XM" = "Look up hormone therapy",
  #                         "S56_24XN" = "Look up gender-related surgeries/procedures",
  #                         "S56_24XO" = "Look up other health information",
  #                         "S56_24XP" = "Look up non-health-related information",
  #                         "S56_24XQ" = "Look for social services",
  #                         "S56_24XR" = "Look up transgender/identity legal information",
  #                         "S56_24XS" = "Other",
  #                         "S56_24XV" = "None"
  #                       )) %>%
  #   mutate(Variable = fct_relevel(factor(Variable, levels = unique(Variable)),
  #                                 "   Other", after = length(Variable) - 2)) %>%
  #   arrange(Variable) %>%
  #   mutate(Variable = as.character(Variable))
)
```

### Table 3a
```{r table3a, include = TRUE}
kable(table3a %>%
        filter(!is.na(Overall))) %>%
  kable_styling(bootstrap_options = c("striped", "condensed")) %>%
  group_rows("Device Use, N (%)", 1, 5) %>%
  # group_rows("Device Use Locations, N (%)", 6, 10) %>%
  # group_rows("Cell Phone Access, N (%)", 11, 15) %>%
  group_rows("Text Messaging:\nFrequency of Sending/Receiving Texts, N (%)", 
             6, 10) %>%
  # group_rows("Text Messaging:\nWho You Text, N (%)", 21, 25) %>%
  # group_rows("Text Messaging:\nWhat You Text About, N (%)", 26, 30) %>%
  group_rows("Email:\nFrequency of Checking Email, N (%)", 11, 15)
  # group_rows("Email:\nWho You Email, N (%)", 36, 40) %>%
  # group_rows("Email:\nWhat You Email About, N (%)", 41, 45)
```

### Table 3b
```{r table3b, include = TRUE}
kable(table3b %>%
        filter(!is.na(Overall))) %>%
  kable_styling(bootstrap_options = c("striped", "condensed")) %>%
  # group_rows("Social Networking (SN) Apps Used, N (%)", 1, 5) %>%
  group_rows("SN Used Most Often, N (%)", 1, 4) %>%
  group_rows("SN Use Frequency, N (%)", 5, 8) %>%
  # group_rows("SN Activities, N (%)", 16, 20) %>%
  # group_rows("Communicate With Whom on SN Apps", 21, 25) %>%
  # group_rows("Communicate About on SN Apps", 26, 30) %>%
  group_rows("PM Use Frequency, N (%)", 9, 13) %>%
  # group_rows("Communicate With Whom on PM Apps", 36, 40) %>%
  # group_rows("Communicate About on PM Apps", 41, 45) %>%
  # group_rows("Dating/Hookup Apps Used", 46, 50) %>%
  # group_rows("Dating/Hookup App Used Most Often", 51, 55) %>%
  # group_rows("Dating/Hookup App Use Frequency", 56, 60) %>%
  # group_rows("Dating/Hookup App Activities", 61, 65) %>%
  group_rows("Frequency of Other Uses of Internet", 14, 18)
  # group_rows("Ever Used the Internet to...", 71, 77)
```

```{r saveWorkbook, eval = FALSE}
wb <- loadWorkbook("DHSB Tables.xlsx")
#Table3a
removeWorksheet(wb, "Table 3a")
addWorksheet(wb, "Table 3a")
writeData(wb, sheet = "Table 3a", table3a)
setColWidths(wb, sheet = "Table 3a", cols = 1:ncol(table3a), widths = "auto")
#Table3b
removeWorksheet(wb, "Table 3b")
addWorksheet(wb, "Table 3b")
writeData(wb, sheet = "Table 3b", table3b)
setColWidths(wb, sheet = "Table 3b", cols = 1:ncol(table3b), widths = "auto")
saveWorkbook(wb, "DHSB Tables.xlsx", overwrite = TRUE)
```

