---
title: "Digital Health-Seeking Behaviors Tables"
author: "Adam Northrup, Data Manager, ETAC"
date: "April 10, 2019"
output: html_document
---
```{r include = FALSE}
knitr::opts_chunk$set(echo = FALSE, include = FALSE, 
                      warning = FALSE, message = FALSE)
#####Read libraries
library(tidyverse)
library(sjlabelled)
library(rio)
library(openxlsx)
library(scales)
library(kableExtra)

#####Load data
setwd("C:/Users/anorthrup/Box Sync/ETAC")
load("Analyses/Digital Health-Seeking Behaviors/ETAC_DHSB/acasi.RData")
source("Analyses/Digital Health-Seeking Behaviors/ETAC_DHSB/DHSB Table Functions.R")
```

```{r}
#####Print "Other" text for each demographic variable
# wb <- createWorkbook()
# for (i in c("GENDERS", "RACEFS", "ORIENTS", "LIVED6LS", "STAY7DS", 
#            "INSUREHS", "SSNDOS", "CNEED3ES", "DISCJS")) {
#   addWorksheet(wb, i)
#   writeData(wb, i, acasi %>%
#               select(SITE1, PID, i) %>%
#               filter(!!sym(i) != "[Skipped]"))
# }
# saveWorkbook(wb, "ACASI Other Text.xlsx", overwrite = TRUE)

#####Format variables and rename
demo <- acasi %>%
  select(-RACE, -starts_with("S56")) %>%
  mutate(`Age Groups` = as.factor(case_when(AGE < 25 ~ "18-24 Years",
                                            AGE >= 25 ~ "25-34 Years")),
         SCREEN5 = fct_recode(as.factor(SCREEN5),
                              "Within past 12 months" = "1", "More than 12 months ago" = "2",
                              "Don't know"   = "7", "Refuse to answer"        = "8"),
         # SEXBRTH = fct_recode(as.factor(SEXBRTH),
         #                      "Male" = "1", "Female" = "2", "Refuse to answer" = "8"),
         ViralSupp_MCD = fct_recode(as.factor(ViralSupp_MCD),
                                    "Not suppressed" = "0",
                                    "Suppressed"     = "1")) %>%
  # mutate_at(vars(JAILL), 
  #           list(as.factor)) %>%
  # mutate_at(vars(JAILL), 
  #           list(fct_recode), "Yes" = "1", "No" = "0", "Don't know" = "7", "Refuse to answer" = "8") %>%
  mutate_at(vars(matches("(CARE)([[:alpha:]]+)(\\d+)")),
            list(~as.factor(case_when(. == 0   ~ "Yes",
                                      . <= 99  ~ "No",
                                      . >  99  ~ "Refuse to answer")))) %>%
  unite("SitePID", SITE_RC, PID, remove = FALSE) %>%
  arrange(SITE_RC, PID) %>%
  # rename(`Sex at Birth` = SEXBRTH,
         # `Relationship Status` = RELSTAT_RC,
         # `Ever Jailed` = JAILL)
```

```{r}
#####Table 1: participant characteristics summary
table1 <- bind_rows(
  #Number of participants
  bind_rows(
    demo %>%
      summarize(Frequency = n()) %>%
      mutate(SITE_RC = "Overall"),
    demo %>%
      group_by(SITE_RC) %>%
      summarize(Frequency = n()) %>%
      mutate(SITE_RC = as.character(SITE_RC))
  ) %>%
    mutate(Frequency = as.character(Frequency)) %>%
    spread(SITE_RC, Frequency) %>%
    mutate(Variable = "Number of Participants") %>%
    select(Variable, Overall, levels(demo$SITE_RC)),
  #Age groups
  table_OneFactor(demo, varString = "Age Groups",
                  varRelevel = c("18-24 Years")),
  #Ethnicity/Race
  table_OneFactor(demo, varString = "RACE_RC", header = "Ethnicity and Race", 
                  varRelevel = c("Latino",
                                 "Black, Not Latino",
                                 "White, Not Latino",
                                 "White Mixed-Race, Not Latino or Black")),
  # #Sex at birth
  # table_OneFactor(demo, varString = "Sex at Birth",
  #                 varRelevel = c("Male")),
  #Gender
  table_OneFactor(demo, varString = "GENDER_RC", header = "Gender Identity",
                  varRelevel = c("Male (cis man)",
                                 "Female (cis woman)",
                                 "Trans-identified")),
  #Orientation
  table_OneFactor(demo, varString = "ORIENT_RC", header = "Sexual Orientation",
                  varRelevel = c("Straight",
                                 "Gay or lesbian",
                                 "Bisexual")),
  #Education
  table_OneFactor(demo, varString = "GRADE_RC", header = "Education",
                  varRelevel = c("High school, equivalent or less",
                                 "Some post-K12")),
  # #Employment
  # table_OneFactor(demo, varString = "EMPLOY_RC", header = "Employment Status"),
  #Income
  table_Continuous(demo, variable = "MONEY_RC", stat = "median", 
                   name = "Income, Last Month"),
  #Residence
  table_OneFactor(demo, varString = "STAY7D_RC", 
                  header = "Residence, Last 7 Days",
                  varRelevel = c("Stable housing",
                                 "Unstable housing",
                                 "Institution"))
  # #Jailed
  # table_OneFactor(demo, varString = "Ever Jailed", header = "Incarceration") %>%
  #   filter(Variable %in% c("   Yes", "Incarceration, N (%)")) %>%
  #   mutate(Variable = str_replace(Variable, "   Yes", "   Ever Jailed"))
)

#####Table 2: participant health care summary
table2 <- bind_rows(
  #HIV Diagnosis
  table_OneFactor(demo, varString = "SCREEN5", header = "HIV Diagnosis",
                  varRelevel = c("Within past 12 months",
                                 "More than 12 months ago")),
  #Viral Suppression
  table_OneFactor(demo, varString = "ViralSupp", header = "Viral Suppression",
                  varRelevel = c("Suppressed")),
  #Insurance
  table_OneFactor(demo, varString = "INSURE_RC", header = "Insurance"),
  #Health care history, 6 months
  bind_rows(
    table_OneFactor(demo, varString = "CARED6", 
                    header = "Recent Health Care") %>%
      filter(Variable != "   No") %>%
      mutate(Variable = replace(Variable, str_which(Variable, "Yes"), 
                                "   Doctor's visit, non-HIV, 6 months")),
    table_OneFactor(demo, header = "Recent Health Care",
                    varString = "CAREHV06") %>%
      filter(str_detect(Variable, "Refuse|Yes")) %>%
      arrange(desc(Variable)) %>%
      mutate(Variable = replace(Variable, str_which(Variable, "Yes"), 
                                "   Doctor's visit, HIV, 6 months"),
             Variable = replace(Variable, str_which(Variable, "Refuse"),
                                                    "      Refuse to answer"))
    ),
  #Youth Health Engagement
  #> Health Access Literacy
  table_Continuous(demo, variable = "HE_RC_HAL",
                   name = "Health Access Literacy, 4 Items", 
                   header = "Youth Health Enagement, Mean (SD)"),
  #> Health Self-Efficacy
  table_Continuous(demo, variable = "HE_RC_HSE", 
                   name = "Health Self-Efficacy, 5 Items"),
  #Provider Empathy
  table_Continuous(demo, variable = "CARE_RC",
                   name = "Provider Empathy, 10 items", 
                   header = "Provider Empathy, Mean (SD)"),
  # #Relationship Status
  # table_OneFactor(demo, varString = "Relationship Status", 
  #                 varRelevel = c("Single",
  #                                "Dating",
  #                                "Partnered/Married")),
  #Social Support
  table_Continuous(demo, variable = "SOCIALS_RC",
                   name = "Social Support, 3 items", 
                   header = "Social Support, Mean (SD)"),
  #HIV-Related Stigma
  table_Continuous(demo, variable = "STIGMA_RC",
                   name = "HIV-Related Stigma, 10 items", 
                   header = "HIV-Related Stigma, Mean (SD)"),
  #HIV Disclosure
  table_ManyBinary(demo, header = "Disclosure of HIV Status",
                   variables = c("DISCA" = "No one",
                                 "DISCB" = "Partner or spouse",
                                 "DISCC" = "Sex partner(s)",
                                 "DISCD" = "Family member(s)",
                                 "DISCE" = "Friend(s)",
                                 "DISCF" = "Health care providers",
                                 "DISCG" = "Coach or teacher",
                                 "DISCH" = "Pastor/Rabbi/Clergy",
                                 "DISCI" = "Staff from site",
                                 "DISCJ" = "Other")),
  #Physical and Mental Health
  table_Continuous(demo, variable = "MENTALH_RC",
                   name = "Mental Health, 3 items",
                   header = "Physical and Mental Health, Mean (SD)"),
  table_Continuous(demo, variable = "MENTALH4",
                   name = "Mental and Physical Health, 1 item"),
  #Substance Use
  table_ManyBinary(demo, header = "Substance Use", n = 0,
                   keep = c("DRUG1LA", "DRUG1LB", "DRUG1LC", "DRUG_RCD_None",
                            "INJECTL"),
                   variables = c("DRUG1LA" = "Alcohol",
                                 "DRUG1LB" = "Tobacco",
                                 "DRUG1LC" = "Marijuana",
                                 "DRUG1LD" = "Synthetic marijuana",
                                 "DRUG1LE" = "Marijuana laced with PCP",
                                 "DRUG1LF" = "Methamphetamine",
                                 "DRUG1LG" = "Amphetamines",
                                 "DRUG1LH" = "Molly, MDMA, Ecstasy",
                                 "DRUG1LI" = "LSD, other hallucinogens",
                                 "DRUG1LJ" = "Poppers, other inhalants",
                                 "DRUG1LK" = "Powder cocaine",
                                 "DRUG1LL" = "Crack cocaine",
                                 "DRUG2LA" = "Heroin",
                                 "DRUG2LB" = "Special K",
                                 "DRUG2LC" = "Primos (marijuana and rock)",
                                 "DRUG2LD" = "Synthetic cathinones (bath salts)",
                                 "DRUG2LE" = "Codeine cough syrup",
                                 "DRUG2LF" = "Painkillers",
                                 "DRUG2LG" = "Tranquilizers",
                                 "DRUG2LH" = "ADHD medication",
                                 "DRUG2LI" = "Over the counter drugs",
                                 "DRUG2LJ" = "Other non-injected drugs",
                                 "DRUG_RCD_None" = "None",
                                 "INJECTL" = "Injected drugs")) %>%
    mutate(Variable = fct_relevel(factor(Variable, levels = unique(Variable)),
                                  "Substance Use, N (%)",
                                  "   Skipped/Refuse/Missing",
                                  "   Alcohol", "   Tobacco", "   Marijuana", 
                                  "   Injected drugs", "   Other")) %>%
    arrange(Variable) %>%
    mutate(Variable = as.character(Variable)),
  #MTUAS
  #> Email Usage
  table_Continuous(demo, variable = "MTUEX_RC",
                   name = "Email usage",
                   header = "Media and Technology Use and Attitudes Subscales"),
  #> Text Messaging
  table_Continuous(demo, variable = "MTUSPX_RC_Text",
                   name = "Text messaging"),
  #> Smartphone Usage
  table_Continuous(demo, variable = "MTUSPX_RC_Smartphone",
                   name = "Smartphone usage"),
  #> Internet Searching
  table_Continuous(demo, variable = "MTUIX_RC",
                   name = "Internet searching"),
  #> General Social Media Usage
  table_Continuous(demo, variable = "MTUSNX_RC",
                   name = "General social media usage"),
  #> Positive Attitudes
  table_Continuous(demo, variable = "MTUAX_RC_Pos",
                   name = "Positive Attitudes Toward Technology"),
  #> Anxieties
  table_Continuous(demo, variable = "MTUAX_RC_Anx",
                   name = "Anxiety and Dependence on Technology"),
  #> Negative Attitudes
  table_Continuous(demo, variable = "MTUAX_RC_Neg",
                   name = "Negative Attitudes Toward Technology")
)
```

### Table 1
```{r include = TRUE}
kable(table1 %>%
        filter(!is.na(Overall)),
      caption = 
        "Table 1. Sociodemographic characteristics of youth and young people living with HIV"
      ) %>%
  kable_styling(bootstrap_options = c("striped", "condensed")) %>%
  group_rows("Age Group, N (%)", 2, 3) %>%
  group_rows("Ethnicity and Race, N (%)", 4, 8) %>%
  group_rows("Gender Identity, N (%)", 9, 12) %>%
  group_rows("Sexual Orientation, N (%)", 13, 16) %>%
  group_rows("Education, N (%)", 17, 19) %>%
  group_rows("Income, Median [IQR]", 20, 20) %>%
  group_rows("Residence, Last 7 Days, N (%)", 21, 24)
```

### Table 2
```{r include = TRUE}
kable(table2 %>%
        filter(!is.na(Overall)),
      caption = "Table 2. HIV-related health, healthcare utilization, and other characteristics that may relate to digital health seeking"
      ) %>%
  kable_styling(bootstrap_options = c("striped", "condensed")) %>%
  group_rows("HIV Diagnosis, N (%)", 1, 3) %>%
  group_rows("Viral Suppression, N (%)", 4, 6) %>%
  group_rows("Insurance, N (%)", 7, 9) %>%
  group_rows("Recent Health Care, N (%)", 10, 12) %>%
  add_indent(c(12)) %>%
  group_rows("Youth Health Enagement, Mean (SD)", 13, 14) %>%
  group_rows("Provider Empathy, Mean (SD)", 15, 15) %>%
  # group_rows("Relationship Status, N (%)", 16, 19) %>%
  group_rows("Social Support, Mean (SD)", 16, 16) %>%
  group_rows("HIV-Related Stigma, Mean (SD)", 17, 17) %>%
  group_rows("Disclosure of HIV Status, N (%)", 18, 27) %>%
  group_rows("Physical and Mental Health, Mean (SD)", 28, 29) %>%
  group_rows("Substance Use, N (%)", 30, 36) %>%
  group_rows("Media and Technology Use and Attitudes Subscales", 37, 44)
```

```{r eval = FALSE}
wb <- loadWorkbook("DHSB Tables.xlsx")
#Table 1
removeWorksheet(wb, "Table 1")
addWorksheet(wb, "Table 1")
writeData(wb, sheet = "Table 1", table1)
setColWidths(wb, sheet = "Table 1", cols = 1:ncol(table1), widths = "auto")
#Table 2
removeWorksheet(wb, "Table 2")
addWorksheet(wb, "Table 2")
writeData(wb, sheet = "Table 2", table2)
setColWidths(wb, sheet = "Table 2", cols = 1:ncol(table2), widths = "auto")

saveWorkbook(wb, "DHSB Tables.xlsx", overwrite = TRUE)
```

### Testing Across Sites
```{r include = TRUE}
table1Chisq <- table1 %>%
  mutate_at(vars(-Variable), list(~as.integer(str_extract(., "(\\d+)"))))
table2Chisq <- table2 %>%
  mutate_at(vars(-Variable), list(~as.integer(str_extract(., "(\\d+)"))))
bind_rows(
  chisq.dhsb(table1Chisq, "Age Group", 
             c("   18-24 Years", "   25-34 Years")),
  chisq.dhsb(table1Chisq, "Ethnicity and Race", 
             c("   Latino", 
               "   Black, Not Latino",
               "   White, Not Latino")),
  chisq.dhsb(table1Chisq, "Gender Identity", 
             c("   Male (cis man)", 
               "   Female (cis woman)",
               "   Trans-identified",
               "   Other gender")),
  chisq.dhsb(table1Chisq, "Sexual Orientation", 
             c("   Straight",
               "   Gay or lesbian",
               "   Bisexual",
               "   Other orientation")),
  chisq.dhsb(table1Chisq, "Education", 
             c("   High school, equivalent or less",
               "   Some post-K12",
               "   College graduate or trade certification")),
  chisq.dhsb(table1Chisq, "Residence, Last 7 Days",
             c("   Stable housing",
               "   Unstable housing",
               "   Institution"))
) %>%
  mutate(Warning = c("No", "Yes", "Yes", "Yes", "Yes", "Yes")) %>%
  kable(., digits = 3,
        caption = "Chi-Square Testing for Categorical Variables Across Site") %>%
  kable_styling(bootstrap_options = c("striped", "condensed"))
bind_rows(
  anova.dhsb(demo, "MONEY_RC_Log", "Income, Last Month"),
  anova.dhsb(demo, "HE_RC_HAL", "Health Access Literacy"),
  anova.dhsb(demo, "HE_RC_HSE", "Health Self-Efficacy"),
  anova.dhsb(demo, "CARE_RC", "Provider Empathy"),
  anova.dhsb(demo, "MENTALH_RC", "Mental Health"),
  anova.dhsb(demo, "MENTALH4_RC", "Physical and Mental Health"),
  anova.dhsb(demo, "MTUEX_RC", "Email Usage"),
  anova.dhsb(demo, "MTUSPX_RC_Text", "Text Messaging"),
  anova.dhsb(demo, "MTUSPX_RC_Smartphone", "Smartphone Usage"),
  anova.dhsb(demo, "MTUIX_RC", "Internet Searching"),
  anova.dhsb(demo, "MTUSNX_RC", "General Social Media Usage"),
  anova.dhsb(demo, "MTUAX_RC_Pos", "Positive Attitudes Toward Technology"),
  anova.dhsb(demo, "MTUAX_RC_Anx", "Anxiety About Being Without Technology or Dependence on Technology"),
  anova.dhsb(demo, "MTUAX_RC_Neg", "Negative Attitudes Toward Technology")
) %>%
  kable(., digits = 3,
        caption = "ANOVA Testing for Continuous Variables Across Site") %>%
  kable_styling(bootstrap_options = c("striped", "condensed"))

```

